# Auto-generated mapping: LAW_SUPP_MAP
# Do not edit by hand

LAW_SUPP_MAP = {100: 'Art. I, Sec. 1 (Delegation of Powers)',
 101: 'Art. I, Sec. 10 (State Restrictions: Bills of Credit, etc.)',
 102: 'Art. I, Sec. 2 (House Composition)',
 103: 'Art. I, Sec. 4 (Elections)',
 105: 'Art. I, Sec. 6 (Speech or Debate Clause)',
 106: 'Art. I, Sec. 7 (Veto/Legislative Process)',
 107: 'Art. I, Sec. 8, Cl. 1 (Taxing/General Welfare)',
 108: 'Art. I, Sec. 8, Cl. 3 (Interstate Commerce)',
 110: 'Art. I, Sec. 8, Cl. 4 (Bankruptcy/Naturalization)',
 111: 'Art. I, Sec. 8, Cl. 11 (War Power)',
 120: 'Art. I, Sec. 8, Cl. 18 (Necessary and Proper Clause)',
 121: 'Art. I, Sec. 9, Cl. 2 (Habeas Corpus)',
 122: 'Art. I, Sec. 9, Cl. 3 (Ex Post Facto/Bill of Attainder)',
 128: 'Art. I, Sec. 10, Cl. 1 (Contract Clause)',
 130: 'Art. II, Sec. 1 (Executive Power)',
 134: 'Art. II, Sec. 2 (Commander in Chief)',
 135: 'Art. II, Sec. 2, Cl. 2 (Appointments/Treaties)',
 136: 'Art. III, Sec. 1 (Judicial Power)',
 139: 'Art. III, Sec. 2 (Case or Controversy)',
 144: 'Art. IV, Sec. 1 (Full Faith and Credit)',
 145: 'Art. IV, Sec. 2, Cl. 1 (Privileges and Immunities)',
 148: 'Art. VI, Cl. 2 (Supremacy Clause)',
 200: 'Bill of Rights (General)',
 201: '1st Amend (Speech, Press, Assembly)',
 202: '1st Amend (Association)',
 203: '1st Amend (Free Exercise of Religion)',
 204: '1st Amend (Establishment Clause)',
 206: '4th Amend (Search and Seizure)',
 208: '5th Amend (Due Process)',
 210: '5th Amend (Miranda/Warnings)',
 211: '5th Amend (Self-incrimination)',
 212: '5th Amend (Takings Clause)',
 213: '5th Amend (Double Jeopardy)',
 214: '5th Amend (Grand Jury)',
 215: '6th Amend (Right to Counsel)',
 216: '6th Amend (Jury Trial)',
 217: '6th Amend (Confrontation Clause)',
 218: '6th Amend (Speedy Trial)',
 219: '6th Amend (Compulsory Process)',
 222: '8th Amend (Cruel and Unusual Punishment)',
 223: '8th Amend (Excessive Bail/Fines)',
 225: '11th Amend (State Sovereign Immunity)',
 229: '13th Amend (Slavery/Involuntary Servitude)',
 231: '14th Amend (Due Process)',
 232: '14th Amend (Equal Protection)',
 233: '14th Amend (Privileges or Immunities)',
 234: '14th Amend (Enforcement Power)',
 235: '15th Amend (Right to Vote)',
 238: "19th Amend (Women's Suffrage)",
 240: '24th Amend (Poll Tax)',
 305: 'Clean Air Act',
 306: 'Administrative Procedure Act (APA)',
 312: 'Civil Rights Act (1964)',
 314: 'Civil Rights Act (1866/1871 - Sec 1983)',
 315: 'Civil Rights Act (1965 - Voting Rights)',
 324: 'ERISA (Pension/Benefits Law)',
 325: 'Fair Labor Standards Act (FLSA)',
 327: 'Federal Arbitration Act',
 332: "Federal Employers' Liability Act (FELA)",
 337: 'Freedom of Information Act (FOIA)',
 342: 'Immigration and Nationality Act',
 350: 'National Labor Relations Act (NLRA)',
 355: 'Occupational Safety and Health Act (OSHA)',
 363: 'RICO Act',
 368: 'Sherman Antitrust Act',
 369: 'Clayton Antitrust Act',
 375: 'Social Security Act',
 379: 'Voting Rights Act of 1965',
 400: 'Federal Rules of Civil Procedure',
 401: 'Federal Rules of Criminal Procedure',
 402: 'Federal Rules of Evidence',
 403: 'Supreme Court Rules',
 500: 'Abstention Doctrine',
 501: 'Retroactive Application of Right',
 502: 'Exclusionary Rule (4th Amend)',
 503: 'Exclusionary Rule (Right to Counsel)',
 504: 'Exclusionary Rule (Miranda)',
 505: 'Harmless Error',
 506: 'Res Judicata / Collateral Estoppel',
 508: 'Writ Improvidently Granted (DIG)',
 509: 'Treaty',
 510: 'Interstate Compact',
 511: 'Executive Order',
 512: 'Territory Statute'}
